from datetime import date
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, field_validator
from supabase import Client

from app.core.deps import get_current_company_id, get_current_user, get_supabase, require_owner_or_admin
from app.services.ledger import JournalLine, UnbalancedJournalEntry, post_journal_entry

router = APIRouter(prefix="/ledger", tags=["Ledger"])


@router.get("/entries")
def get_ledger_entries(
    source_type: str = Query(..., description="e.g. 'expense', 'salary_payment', 'invoice', 'payment'"),
    source_id: str = Query(...),
    supabase: Client = Depends(get_supabase),
):
    """
    Returns the journal entry (or entries) and their lines behind one
    source record -- e.g. source_type=expense&source_id=<id> shows exactly
    what posted when that expense was logged. Powers a "View ledger" action
    from any list page without needing a dedicated endpoint per table.
    """
    entries = (
        supabase.table("journal_entries")
        .select("*")
        .eq("source_type", source_type)
        .eq("source_id", source_id)
        .execute()
        .data
    )
    entry_ids = [e["id"] for e in entries]
    lines = []
    if entry_ids:
        lines = (
            supabase.table("journal_lines")
            .select("*")
            .in_("journal_entry_id", entry_ids)
            .execute()
            .data
        )
    return {"entries": entries, "lines": lines}


# ---------------------------------------------------------------------------
# Manual / adjustment journal entries
# ---------------------------------------------------------------------------
class ManualJournalLine(BaseModel):
    account_id: str
    direction: str  # "debit" | "credit"
    amount: float
    building_id: Optional[str] = None
    room_id: Optional[str] = None
    owner_id: Optional[str] = None
    tenant_id: Optional[str] = None

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: str) -> str:
        if v not in ("debit", "credit"):
            raise ValueError("direction must be 'debit' or 'credit'")
        return v

    @field_validator("amount")
    @classmethod
    def validate_amount(cls, v: float) -> float:
        if v <= 0:
            raise ValueError("amount must be greater than zero")
        return v


class ManualJournalEntryCreate(BaseModel):
    entry_date: date
    description: str
    lines: list[ManualJournalLine]


@router.post("/manual-entry", status_code=201)
def create_manual_journal_entry(
    payload: ManualJournalEntryCreate,
    supabase: Client = Depends(get_supabase),
    company_id: str = Depends(get_current_company_id),
    user: dict = Depends(get_current_user),
    _perm: None = Depends(require_owner_or_admin),
):
    """
    Posts a manual/adjustment journal entry for anything that isn't already
    generated by an invoice, payment, expense, salary, or deposit action --
    e.g. correcting a mis-posted amount, recording a one-off write-off, or
    any other book adjustment. Goes through the exact same post_journal_entry()
    engine every other money-moving endpoint uses, so debits=credits is
    still enforced and the entry is fully reversible later like any other.

    Owner/admin only, since this writes directly to the books without the
    usual guardrails a business-object endpoint (invoice, payment, etc.)
    provides.
    """
    if len(payload.lines) < 2:
        raise HTTPException(status_code=400, detail="A journal entry needs at least two lines.")

    account_ids = {l.account_id for l in payload.lines}
    accounts = (
        supabase.table("chart_of_accounts")
        .select("id")
        .eq("company_id", company_id)
        .in_("id", list(account_ids))
        .execute()
        .data
    )
    found_ids = {a["id"] for a in accounts}
    missing = account_ids - found_ids
    if missing:
        raise HTTPException(status_code=400, detail="One or more selected accounts were not found.")

    journal_lines: list[JournalLine] = [
        {
            "account_id": l.account_id,
            "direction": l.direction,
            "amount": l.amount,
            "building_id": l.building_id,
            "room_id": l.room_id,
            "owner_id": l.owner_id,
            "tenant_id": l.tenant_id,
        }
        for l in payload.lines
    ]

    try:
        entry = post_journal_entry(
            supabase,
            company_id=company_id,
            entry_date=str(payload.entry_date),
            source_type="manual_adjustment",
            source_id=None,
            description=payload.description,
            lines=journal_lines,
            created_by=user["user_id"],
        )
    except UnbalancedJournalEntry as e:
        raise HTTPException(status_code=400, detail=str(e))

    return entry
