from datetime import date
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, field_validator
from supabase import Client

from app.core.deps import get_current_company_id, get_current_user, get_supabase, require_owner_or_admin
from app.crud.generic import write_audit_log
from app.services.ledger import JournalLine, UnbalancedJournalEntry, post_journal_entry

router = APIRouter(prefix="/ledger", tags=["Ledger"])


@router.get("/entries")
def get_ledger_entries(
    source_type: str = Query(..., description="e.g. 'expense', 'salary_payment', 'invoice', 'payment'"),
    source_id: str = Query(...),
    supabase: Client = Depends(get_supabase),
):
    """
    Returns the journal entry (or entries) and their lines behind one
    source record -- e.g. source_type=expense&source_id=<id> shows exactly
    what posted when that expense was logged. Powers a "View ledger" action
    from any list page without needing a dedicated endpoint per table.
    """
    entries = (
        supabase.table("journal_entries")
        .select("*")
        .eq("source_type", source_type)
        .eq("source_id", source_id)
        .execute()
        .data
    )
    entry_ids = [e["id"] for e in entries]
    lines = []
    if entry_ids:
        lines = (
            supabase.table("journal_lines")
            .select("*")
            .in_("journal_entry_id", entry_ids)
            .execute()
            .data
        )
    return {"entries": entries, "lines": lines}


# ---------------------------------------------------------------------------
# Manual / adjustment journal entries
# ---------------------------------------------------------------------------
class ManualJournalLine(BaseModel):
    account_id: str
    direction: str  # "debit" | "credit"
    amount: float
    building_id: Optional[str] = None
    room_id: Optional[str] = None
    owner_id: Optional[str] = None
    tenant_id: Optional[str] = None

    @field_validator("direction")
    @classmethod
    def validate_direction(cls, v: str) -> str:
        if v not in ("debit", "credit"):
            raise ValueError("direction must be 'debit' or 'credit'")
        return v

    @field_validator("amount")
    @classmethod
    def validate_amount(cls, v: float) -> float:
        if v <= 0:
            raise ValueError("amount must be greater than zero")
        return v


class ManualJournalEntryCreate(BaseModel):
    entry_date: date
    description: str
    lines: list[ManualJournalLine]


@router.post("/manual-entry", status_code=201)
def create_manual_journal_entry(
    payload: ManualJournalEntryCreate,
    supabase: Client = Depends(get_supabase),
    company_id: str = Depends(get_current_company_id),
    user: dict = Depends(get_current_user),
    _perm: None = Depends(require_owner_or_admin),
):
    """
    Posts a manual/adjustment journal entry for anything that isn't already
    generated by an invoice, payment, expense, salary, or deposit action --
    e.g. correcting a mis-posted amount, recording a one-off write-off, or
    any other book adjustment. Goes through the exact same post_journal_entry()
    engine every other money-moving endpoint uses, so debits=credits is
    still enforced and the entry is fully reversible later like any other.

    Owner/admin only, since this writes directly to the books without the
    usual guardrails a business-object endpoint (invoice, payment, etc.)
    provides.
    """
    if len(payload.lines) < 2:
        raise HTTPException(status_code=400, detail="A journal entry needs at least two lines.")

    account_ids = {l.account_id for l in payload.lines}
    accounts = (
        supabase.table("chart_of_accounts")
        .select("id")
        .eq("company_id", company_id)
        .in_("id", list(account_ids))
        .execute()
        .data
    )
    found_ids = {a["id"] for a in accounts}
    missing = account_ids - found_ids
    if missing:
        raise HTTPException(status_code=400, detail="One or more selected accounts were not found.")

    journal_lines: list[JournalLine] = [
        {
            "account_id": l.account_id,
            "direction": l.direction,
            "amount": l.amount,
            "building_id": l.building_id,
            "room_id": l.room_id,
            "owner_id": l.owner_id,
            "tenant_id": l.tenant_id,
        }
        for l in payload.lines
    ]

    try:
        entry = post_journal_entry(
            supabase,
            company_id=company_id,
            entry_date=str(payload.entry_date),
            source_type="manual_adjustment",
            source_id=None,
            description=payload.description,
            lines=journal_lines,
            created_by=user["user_id"],
        )
    except UnbalancedJournalEntry as e:
        raise HTTPException(status_code=400, detail=str(e))

    return entry


# ---------------------------------------------------------------------------
# Editing manual journal entries
#
# Deliberately narrow: this ONLY works for entries created through
# POST /ledger/manual-entry above (source_type == "manual_adjustment" and
# source_id is null). Every entry generated by a business action -- a
# lease, invoice, payment, expense, salary payment, or deposit refund --
# must still go through reverse_journal_entry() instead of being edited in
# place. Editing those directly would let the journal drift out of sync
# with the record that actually generated it (e.g. an invoice's total no
# longer matching its own journal lines), which is exactly what the
# reversal-based-immutability design (schema_patch_016) was built to
# prevent. That guarantee stays fully intact for every non-manual entry;
# this only opens a narrow, audited exception for hand-entered ones.
# ---------------------------------------------------------------------------
def _account_label_map(supabase: Client, company_id: str, account_ids: set[str]) -> dict[str, str]:
    if not account_ids:
        return {}
    accounts = (
        supabase.table("chart_of_accounts")
        .select("id, code, name")
        .eq("company_id", company_id)
        .in_("id", list(account_ids))
        .execute()
        .data
    )
    return {a["id"]: f"{a['code']} {a['name']}" for a in accounts}


def _summarize_lines(lines: list[dict], label_map: dict[str, str]) -> str:
    parts = []
    for l in lines:
        label = label_map.get(l["account_id"], l["account_id"])
        direction = "Dr" if l["direction"] == "debit" else "Cr"
        parts.append(f"{label} {direction} Rs {float(l['amount']):,.2f}")
    return "; ".join(parts)


@router.get("/manual-entries")
def list_manual_journal_entries(
    supabase: Client = Depends(get_supabase),
    company_id: str = Depends(get_current_company_id),
):
    """
    Header rows (not per-line) for every manual/adjustment entry, newest
    first -- used to power the editable list on the journal entry page.
    Deliberately a separate, dedicated endpoint rather than reusing
    /financials/journal (which is per-line and built for filtering/reporting,
    not for identifying a specific entry to edit).
    """
    entries = (
        supabase.table("journal_entries")
        .select("*")
        .eq("company_id", company_id)
        .eq("source_type", "manual_adjustment")
        .order("entry_date", desc=True)
        .order("created_at", desc=True)
        .execute()
        .data
    )
    entry_ids = [e["id"] for e in entries]
    lines = []
    if entry_ids:
        lines = (
            supabase.table("journal_lines")
            .select("*")
            .in_("journal_entry_id", entry_ids)
            .execute()
            .data
        )
    label_map = _account_label_map(supabase, company_id, {l["account_id"] for l in lines})
    lines_by_entry: dict[str, list[dict]] = {}
    for l in lines:
        lines_by_entry.setdefault(l["journal_entry_id"], []).append(l)

    for e in entries:
        entry_lines = lines_by_entry.get(e["id"], [])
        e["total_amount"] = round(sum(float(l["amount"]) for l in entry_lines if l["direction"] == "debit"), 2)
        e["lines_summary"] = _summarize_lines(entry_lines, label_map)

    return entries


@router.get("/manual-entry/{entry_id}")
def get_manual_journal_entry(
    entry_id: str,
    supabase: Client = Depends(get_supabase),
    company_id: str = Depends(get_current_company_id),
):
    entry = (
        supabase.table("journal_entries")
        .select("*")
        .eq("id", entry_id)
        .eq("company_id", company_id)
        .single()
        .execute()
    )
    if not entry.data:
        raise HTTPException(status_code=404, detail="Journal entry not found")
    if entry.data["source_type"] != "manual_adjustment":
        raise HTTPException(
            status_code=400,
            detail="Only manually-created journal entries can be opened for editing.",
        )
    lines = (
        supabase.table("journal_lines")
        .select("*")
        .eq("journal_entry_id", entry_id)
        .execute()
        .data
    )
    return {**entry.data, "lines": lines}


@router.patch("/manual-entry/{entry_id}")
def update_manual_journal_entry(
    entry_id: str,
    payload: ManualJournalEntryCreate,
    supabase: Client = Depends(get_supabase),
    company_id: str = Depends(get_current_company_id),
    user: dict = Depends(get_current_user),
    _perm: None = Depends(require_owner_or_admin),
):
    """
    Edits a manual journal entry IN PLACE (replaces its lines) instead of
    reversing and re-posting -- allowed ONLY when source_type ==
    'manual_adjustment' and source_id is null, i.e. it was created via
    POST /ledger/manual-entry (the "New Journal Entry" button), never for
    an entry generated by a lease/invoice/payment/expense/salary/deposit
    action. Debits=credits is re-validated exactly as on create. Every edit
    writes a before/after snapshot to audit_log (same table/pattern as
    every other edit in this app), viewable via the existing HistoryPanel
    component at table_name='journal_entries', record_id=<entry id>.
    """
    existing = (
        supabase.table("journal_entries")
        .select("*")
        .eq("id", entry_id)
        .eq("company_id", company_id)
        .single()
        .execute()
    )
    if not existing.data:
        raise HTTPException(status_code=404, detail="Journal entry not found")

    entry = existing.data
    if entry["source_type"] != "manual_adjustment" or entry.get("source_id") is not None:
        raise HTTPException(
            status_code=400,
            detail=(
                "Only manually-created journal entries can be edited directly. "
                "Entries generated by a lease, invoice, payment, expense, salary, "
                "or deposit action must be corrected by reversing them instead."
            ),
        )
    if entry.get("status") == "reversed":
        raise HTTPException(
            status_code=400, detail="This entry has already been reversed and can't be edited."
        )

    if len(payload.lines) < 2:
        raise HTTPException(status_code=400, detail="A journal entry needs at least two lines.")

    total_debits = round(sum(l.amount for l in payload.lines if l.direction == "debit"), 2)
    total_credits = round(sum(l.amount for l in payload.lines if l.direction == "credit"), 2)
    if total_debits != total_credits:
        raise HTTPException(status_code=400, detail="Debits must equal credits.")
    if total_debits == 0:
        raise HTTPException(status_code=400, detail="Entry has zero amount -- nothing to post.")

    new_account_ids = {l.account_id for l in payload.lines}
    accounts = (
        supabase.table("chart_of_accounts")
        .select("id")
        .eq("company_id", company_id)
        .in_("id", list(new_account_ids))
        .execute()
        .data
    )
    missing = new_account_ids - {a["id"] for a in accounts}
    if missing:
        raise HTTPException(status_code=400, detail="One or more selected accounts were not found.")

    old_lines = (
        supabase.table("journal_lines").select("*").eq("journal_entry_id", entry_id).execute().data
    )

    updated = (
        supabase.table("journal_entries")
        .update({"entry_date": str(payload.entry_date), "description": payload.description})
        .eq("id", entry_id)
        .execute()
        .data[0]
    )

    # Replace lines wholesale (delete + reinsert) rather than diffing row by
    # row -- simplest way to also handle lines being added or removed, and
    # matches how post_journal_entry() itself writes lines on create.
    supabase.table("journal_lines").delete().eq("journal_entry_id", entry_id).execute()
    new_line_rows = [
        {
            "company_id": company_id,
            "journal_entry_id": entry_id,
            "account_id": l.account_id,
            "direction": l.direction,
            "amount": l.amount,
            "building_id": l.building_id,
            "room_id": l.room_id,
            "owner_id": l.owner_id,
            "tenant_id": l.tenant_id,
        }
        for l in payload.lines
    ]
    new_lines = supabase.table("journal_lines").insert(new_line_rows).execute().data

    label_map = _account_label_map(
        supabase, company_id, {l["account_id"] for l in old_lines} | new_account_ids
    )
    write_audit_log(
        supabase,
        company_id,
        user["user_id"],
        "update",
        "journal_entries",
        entry_id,
        before={
            "entry_date": entry["entry_date"],
            "description": entry["description"],
            "lines": _summarize_lines(old_lines, label_map),
        },
        after={
            "entry_date": str(payload.entry_date),
            "description": payload.description,
            "lines": _summarize_lines(new_lines, label_map),
        },
    )

    return {**updated, "lines": new_lines}
